# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('areaname', models.CharField(blank=True, max_length=40, null=True, verbose_name='名称')),
                ('areadescribe', models.TextField(blank=True, null=True, verbose_name='活动专区描述')),
                ('areaorder', models.SmallIntegerField(blank=True, choices=[(1, '时间正序'), (2, '时间反序')], default=1, verbose_name='排序方式')),
            ],
            options={
                'verbose_name': '首页活动专区表',
                'verbose_name_plural': '首页活动专区表',
            },
        ),
        migrations.CreateModel(
            name='Activitygoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('areaadress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm_goods.ActivityArea', verbose_name='专区ID')),
            ],
            options={
                'verbose_name': '首页活动专区表',
                'verbose_name_plural': '首页活动专区表',
            },
        ),
        migrations.CreateModel(
            name='FirstActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('activityname', models.CharField(blank=True, max_length=50, null=True, verbose_name='活动名称')),
                ('activitypicture', models.ImageField(blank=True, null=True, upload_to='goods/activity/%Y%m/%d', verbose_name='活动图片')),
                ('activityurl', models.URLField(blank=True, null=True, verbose_name='活动url地址')),
            ],
            options={
                'verbose_name': '首页活动表',
                'verbose_name_plural': '首页活动表',
            },
        ),
        migrations.CreateModel(
            name='FirstBroadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('firstname', models.CharField(blank=True, max_length=50, null=True, verbose_name='首页名称')),
                ('goodsSku', models.IntegerField(verbose_name='商品SKUID')),
                ('firstpicture', models.ImageField(blank=True, upload_to='goods/first/%Y%m/%d', verbose_name='图片')),
                ('firstorder', models.SmallIntegerField(choices=[(1, '时间正序'), (2, '时间反序')], default=1, verbose_name='排序方式')),
            ],
            options={
                'verbose_name': '首页轮播商品表',
                'verbose_name_plural': '首页轮播商品表',
            },
        ),
        migrations.CreateModel(
            name='GoodsClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('classifyname', models.CharField(max_length=20, verbose_name='分类名')),
                ('classifyabstract', models.TextField(blank=True, null=True, verbose_name='分类简介')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
            },
        ),
        migrations.CreateModel(
            name='GoodsPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('pictureaddress', models.ImageField(blank=True, null=True, upload_to='goods/%Y%m/%d', verbose_name='图片地址')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
            },
        ),
        migrations.CreateModel(
            name='GoodsSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('goodsname', models.CharField(max_length=50, verbose_name='商品名称')),
                ('goodsabstract', models.CharField(blank=True, max_length=100, null=True, verbose_name='商品简介')),
                ('goodprice', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='商品价格')),
                ('goodsstock', models.IntegerField(blank=True, default=0, verbose_name='商品库存')),
                ('goodssales', models.FloatField(blank=True, default=0, verbose_name='商品销量')),
                ('logoaddress', models.ImageField(blank=True, upload_to='goods/%Y%m/%d', verbose_name='商品封面图')),
                ('goodsshow', models.BooleanField(default=1, verbose_name='产品是否上架')),
            ],
            options={
                'verbose_name': '商品SKU表',
                'verbose_name_plural': '商品SKU表',
            },
        ),
        migrations.CreateModel(
            name='GoodsSPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('SPUname', models.CharField(blank=True, max_length=100, verbose_name='商品SPU名称')),
                ('SPUdetail', models.TextField(blank=True, null=True, verbose_name='SPU详情')),
            ],
            options={
                'verbose_name': '商品SPU',
                'verbose_name_plural': '商品SPU',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('unitname', models.CharField(max_length=20, verbose_name='单位名称')),
            ],
            options={
                'verbose_name': '计量单位表',
                'verbose_name_plural': '计量单位表',
            },
        ),
        migrations.AddField(
            model_name='goodssku',
            name='goodsSPUid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm_goods.GoodsSPU', verbose_name='商品SPUid'),
        ),
        migrations.AddField(
            model_name='goodssku',
            name='goodsunit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sm_goods.Unit', verbose_name='商品单位'),
        ),
        migrations.AddField(
            model_name='goodssku',
            name='goodsverboseid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm_goods.GoodsClassify', verbose_name='商品分类ID'),
        ),
        migrations.AddField(
            model_name='goodspicture',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sm_goods.GoodsSKU', verbose_name='商品ID'),
        ),
        migrations.AddField(
            model_name='activitygoods',
            name='goodssku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm_goods.GoodsSKU', verbose_name='商品SKU ID'),
        ),
    ]
