# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sm_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activityarea',
            table='ActivityArea',
        ),
        migrations.AlterModelTable(
            name='activitygoods',
            table='Activitygoods',
        ),
        migrations.AlterModelTable(
            name='firstactivity',
            table='FirstActivity',
        ),
        migrations.AlterModelTable(
            name='firstbroadcast',
            table='FirstBroadcast',
        ),
    ]
