# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sm_goods', '0002_auto_20180812_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitygoods',
            options={'verbose_name': '首页专区活动商品', 'verbose_name_plural': '首页专区活动商品'},
        ),
    ]
