# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_goods', '0003_auto_20180812_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitygoods',
            name='goodssku',
            field=models.SmallIntegerField(verbose_name='商品SKU ID'),
        ),
    ]
