# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('nickname', models.CharField(blank=True, max_length=15, null=True, verbose_name='昵称')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='电话号码')),
                ('pwd', models.CharField(max_length=64, verbose_name='密码')),
                ('sex', models.SmallIntegerField(blank=True, choices=[(1, '男'), (2, '女'), (3, '不详')], null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('hometown', models.CharField(blank=True, max_length=20, null=True)),
                ('picture', models.ImageField(default='default/shop1.png', upload_to='user/%Y%m/%d', verbose_name='头像LOGO')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
            },
        ),
    ]
