# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='picture',
            field=models.ImageField(default='shop1.png', upload_to='user_head/%Y%m/%d', verbose_name='头像LOGO'),
        ),
    ]
